### ISSUE TITLE
start error with latest code

### ISSUE THREAD

**Issue by mgrouch** [pypilot/pypilot#129]
```


Mar  5 21:55:21 lysmarine pypilot[515]: Traceback (most recent call last):
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/local/bin/pypilot", line 11, in <module>
Mar  5 21:55:21 lysmarine pypilot[515]:     load_entry_point('pypilot==0.34', 'console_scripts', 'pypilot')()
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_e
ntry_point
Mar  5 21:55:21 lysmarine pypilot[515]:     return get_distribution(dist).load_entry_point(group, name)
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_
entry_point
Mar  5 21:55:21 lysmarine pypilot[515]:     return ep.load()
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
Mar  5 21:55:21 lysmarine pypilot[515]:     return self.resolve()
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resol
ve
Mar  5 21:55:21 lysmarine pypilot[515]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/local/lib/python3.7/dist-packages/pypilot/autopilot.py", line 21, in <mod
ule>
Mar  5 21:55:21 lysmarine pypilot[515]:     from boatimu import *
Mar  5 21:55:21 lysmarine pypilot[515]:   File "/usr/local/lib/python3.7/dist-packages/pypilot/boatimu.py", line 459
Mar  5 21:55:21 lysmarine pypilot[515]:     srh = math.sin(rh), crh = math.cos(rh)
Mar  5 21:55:21 lysmarine pypilot[515]:          ^
Mar  5 21:55:21 lysmarine pypilot[515]: SyntaxError: can't assign to function call


```

**Comment by mgrouch** [comment]
sorry. I think I pulled wrong commit.
