### ISSUE TITLE
NameError: name 'filename' is not defined

### ISSUE THREAD

**Issue by FredericGuilbault** [pypilot/pypilot#19]
When starting pypilot_webapp from the CLI, if no port is specified as first argument. It seem to be looking for a file but I don't see what should be defining the file name., or what should be the filename. 

In anycase, instead of using the default value defined at line 16. It crash:

```
Traceback (most recent call last):
  File "/usr/local/bin/pypilot_webapp", line 11, in <module>
    load_entry_point('pypilot==0.2', 'console_scripts', 'pypilot_webapp')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pypilot-0.2-py2.7-linux-armv7l.egg/webapp/webapp.py", line 20, in <module>
    file = open(filename, 'r')
NameError: name 'filename' is not defined
```

**Comment by seandepagnier** [comment]
this was a very recent new bug, thanks for reporting, it's fixed now
