### ISSUE TITLE
pypilot_web import error 'url_quote' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot#227]
Pypilot 0.52 freshly pulled from github on a raspberry: fail to start pypilot_web:

```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/dist-packages/werkzeug/urls.py)
```

**Comment by marcobergman** [comment]
```
pi@openplotter:~/pypilot $ pypilot_web
Traceback (most recent call last):
  File "/usr/local/bin/pypilot_web", line 33, in <module>
    sys.exit(load_entry_point('pypilot==0.52', 'console_scripts', 'pypilot_web')())
  File "/usr/local/bin/pypilot_web", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/pypilot/web/web.py", line 10, in <module>
    from flask import Flask, render_template, session, request, Markup
  File "/home/pi/.local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/pi/.local/lib/python3.9/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/dist-packages/werkzeug/urls.py)

```

**Comment by marcobergman** [comment]
I'm getting the same error when I simply run flask:

```
pi@openplotter:~/pypilot $ flask
Traceback (most recent call last):
  File "/home/pi/.local/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/home/pi/.local/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/home/pi/.local/lib/python3.9/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/home/pi/.local/lib/python3.9/site-packages/flask/helpers.py", line 14, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/dist-packages/werkzeug/urls.py)
```

**Comment by marcobergman** [comment]
pi@openplotter:~/pypilot $ pip3 list| grep -Ei "flask|werkzeug"
Flask                       2.0.0
flask-babel                 4.0.0
Flask-SocketIO              5.0.0
werkzeug                    3.0.2

**Comment by marcobergman** [comment]
It can be solved by reinstalling the whole OS, then reinstalling pypilot, so it's not a pypilot issue. I don't know how I seem to be getting into such a situation but for now the issue can be closed.
