### ISSUE TITLE
pypilot modules not found

### ISSUE THREAD

**Issue by sailoog** [pypilot/pypilot#52]
after last changes GUI issues are fixed but running pypilot you get these errors:

```
pi@openplotter:~ $ pypilot
ERROR loading pilot.py name 'RangeProperty' is not defined ,  No module named 'pilot'
ERROR loading learning.py cannot import name 'AutopilotPilot' from 'autopilot' (/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py) ,  No module named 'learning'
ERROR loading basic.py No module named 'pilot' ,  No module named 'basic'
ERROR loading absolute.py cannot import name 'AutopilotPilot' from 'autopilot' (/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py) ,  No module named 'absolute'
ERROR loading wind.py cannot import name 'AutopilotPilot' from 'autopilot' (/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py) ,  No module named 'wind'
ERROR loading simple.py No module named 'pilot' ,  No module named 'simple'
loading servo calibration /home/pi/.pypilot/servocalibration
WARNING: using default servo calibration!!
Loaded Pilots: []
set ap.pilot to invalid enum value basic
set ap.pilot to invalid enum value basic
warning: failed to open special file /dev/watchdog0 for writing
         cannot stroke the watchdog
connected to gpsd
set ap.pilot to invalid enum value basic
Settings file RTIMULib.ini loaded
Using settings file RTIMULib.ini
Detected MPU9250/MPU9255 at standard address
Using fusion algorithm Kalman STATE4
IMU Name: MPU-925x
min/max compass calibration not in use
Using ellipsoid compass calibration
Using accel calibration
autopilot failed to read imu at time: 1581092743.0715694
Traceback (most recent call last):
  File "/usr/local/bin/pypilot", line 11, in <module>
    load_entry_point('pypilot==0.15', 'console_scripts', 'pypilot')()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 404, in main
    ap.run()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 217, in run
    self.iteration()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 343, in iteration
    self.adjust_mode(pilot)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 221, in adjust_mode
    newmode = pilot.best_mode(self.preferred_mode.value)
AttributeError: 'NoneType' object has no attribute 'best_mode'
got signal atexit cleaning up
got signal 15 cleaning up
got signal 15 cleaning up
Process Process-1:
Process GpsProcess-5:
got signal 15 cleaning up
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/signalk/pipeserver.py", line 154, in pipe_server_process
    time.sleep(.1)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
Exception ignored in: <function SignalKPipeServerClient.__del__ at 0xb5cfac90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/signalk/pipeserver.py", line 68, in __del__
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/gpsd.py", line 68, in gps_process
    self.read(pipe)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/gpsd.py", line 41, in read
    gpsdata = self.gpsd.next()
  File "/usr/local/lib/python3.7/dist-packages/gps/gps.py", line 301, in next
    return self.__next__()
  File "/usr/local/lib/python3.7/dist-packages/gps/gps.py", line 292, in __next__
    if self.read() == -1:
  File "/usr/local/lib/python3.7/dist-packages/gps/gps.py", line 281, in read
    status = gpscommon.read(self)
  File "/usr/local/lib/python3.7/dist-packages/gps/client.py", line 115, in read
    frag = self.sock.recv(8192)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
    super(SignalKPipeServerClient, self).__del__()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/signalk/server.py", line 69, in __del__
    self.StorePersistentValues()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/signalk/server.py", line 81, in StorePersistentValues
    if not name in self.persistent_data or value.value != self.persistent_data[name]:
AttributeError: 'EnumProperty' object has no attribute 'value'
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/calibration_fit.py", line 575, in CalibrationProcess
    time.sleep(2)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
got signal 17 cleaning up
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
got signal 15 cleaning up
Process NmeaBridgeProcess-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/nmea.py", line 588, in process
    time.sleep(2)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
closing autopilot
pi@openplotter:~ $ MPU-925x init complete
got signal 15 cleaning up
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/boatimu.py", line 83, in imu_process
    if not rtimu.IMUInit():
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 109, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
```

**Comment by sailoog** [comment]
FYI, after Commits on Feb 9, 2020 still errors running pypilot

```
ERROR loading learning.py invalid syntax (learning.py, line 54) ,  No module named 'learning'
ERROR loading basic.py No module named 'pilot' ,  No module named 'basic'
ERROR loading absolute.py No module named 'pilot' ,  No module named 'absolute'
ERROR loading wind.py No module named 'pilot' ,  No module named 'wind'
ERROR loading simple.py No module named 'pilot' ,  No module named 'simple'
2020-02-10 18:09:06.723500: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/pypilot", line 11, in <module>
    load_entry_point('pypilot==0.15', 'console_scripts', 'pypilot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 26, in <module>
    import tacking, servo
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/servo.py", line 17, in <module>
    import autopilot
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/autopilot.py", line 94, in <module>
    import pilots
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.15-py3.7-linux-armv7l.egg/pypilot/pilots/__init__.py", line 28, in <module>
    default.append(mod.pilot)
AttributeError: module 'pilots.intellect' has no attribute 'pilot'
```
