### ISSUE TITLE
Crash when no imu is connected

### ISSUE THREAD

**Issue by Fixh1** [pypilot/pypilot#8]
I am still waiting for an IMU, so am testing without it. but I encountered a bug there...
in 
/usr/local/lib/python2.7/site/packages/lcd/client.py
the error message in fittext :
"compass or gyro failure!"
is not processed correctly 

The client.py crashes and restarts, 
the log file says:

2018-06-11_20:34:06.74833 fittext ERROR
2018-06-11_20:34:06.74837 compass or gyro failure! True 0
2018-06-11_20:34:06.74865 Traceback (most recent call last):
2018-06-11_20:34:06.74893   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 1236, in <module>
2018-06-11_20:34:06.75153     main()
2018-06-11_20:34:06.75209   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 1233, in main
2018-06-11_20:34:06.75784     idle()
2018-06-11_20:34:06.75845   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 1194, in idle
2018-06-11_20:34:06.76091     lcdclient.display()
2018-06-11_20:34:06.76147   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 903, in display
2018-06-11_20:34:06.76409     self.display_page()
2018-06-11_20:34:06.76468   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 661, in display_control
2018-06-11_20:34:06.76621     self.fittext(r, _('ERROR\ncompass or gyro failure!'), True, black)
2018-06-11_20:34:06.76678   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 463, in fittext
2018-06-11_20:34:06.76797     metrics = map(lambda word : (word, font.draw(self.surface, False, word, metric_size, self.bw)), words)
2018-06-11_20:34:06.76854   File "/usr/local/lib/python2.7/site-packages/lcd/client.py", line 463, in <lambda>
2018-06-11_20:34:06.76977     metrics = map(lambda word : (word, font.draw(self.surface, False, word, metric_size, self.bw)), words)
2018-06-11_20:34:06.77031   File "/usr/local/lib/python2.7/site-packages/lcd/font.py", line 60, in draw
2018-06-11_20:34:06.77085     font[c] = create_character(os.path.abspath(os.path.dirname(__file__)) + "/font.ttf", size, c, surface.bypp, crop, bw)
2018-06-11_20:34:06.77139   File "/usr/local/lib/python2.7/site-packages/lcd/font.py", line 85, in create_character
2018-06-11_20:34:06.77192     ifont = ImageFont.truetype(fontpath, size)
2018-06-11_20:34:06.77244   File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 239, in truetype
2018-06-11_20:34:06.77332     return FreeTypeFont(font, size, index, encoding)
2018-06-11_20:34:06.77438   File "/usr/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 128, in __init__
2018-06-11_20:34:06.77503     self.font = core.getfont(font, size, index, encoding)
2018-06-11_20:34:06.77570 IOError: cannot open resource
~

I am running the image of 18062018

**Comment by seandepagnier** [comment]
Fixed by next version of tinypilot
