### ISSUE TITLE
'pypilot_hat none' gives error (when no hat attached)

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot#87]
Openplotter image, latest git clone:

pi@openplotter:~/pypilot $ pypilot_hat none
have gpio for raspberry pi
loading config file: /home/pi/.pypilot/hat.conf
failed to load /proc/device-tree/hat/custom_0 : [Errno 2] No such file or directory: '/proc/device-tree/hat/custom_0'
overriding driver default  to command line none
Traceback (most recent call last):
  File "/usr/local/bin/pypilot_hat", line 11, in <module>
    load_entry_point('pypilot==0.24', 'console_scripts', 'pypilot_hat')()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.24-py3.7-linux-armv7l.egg/pypilot/hat/hat.py", line 435, in main
    hat = Hat()
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.24-py3.7-linux-armv7l.egg/pypilot/hat/hat.py", line 236, in __init__
    self.lcd = lcd.LCD(self)
  File "/usr/local/lib/python3.7/dist-packages/pypilot-0.24-py3.7-linux-armv7l.egg/pypilot/hat/lcd.py", line 131, in __init__
    if screen:
UnboundLocalError: local variable 'screen' referenced before assignment

**Comment by marcobergman** [comment]
I'm not sure if you can see the changes I made. Let me know if you want me to make an explicit PR.

**Comment by marcobergman** [comment]
Changes merged, problem solved.
